#include "arduino_secrets.h"
/* 
  Sketch generated by the Arduino IoT Cloud Thing "Untitled"
  https://create.arduino.cc/cloud/things/a861a8f1-7954-46a2-b796-d0b485b53468 

  Arduino IoT Cloud Variables description

  The following variables are automatically generated and updated when changes are made to the Thing

  CloudLight lED01;
  CloudTemperatureSensor temperature;
  int flame;
  CloudRelativeHumidity humidity;
  bool door;

  Variables which are marked as READ/WRITE in the Cloud Thing will also have functions
  which are called when their values are changed from the Dashboard.
  These functions are generated with the Thing and added at the end of this sketch.
*/

#include "thingProperties.h"
#include "DHT.h"

#define DHTPIN 13
#define DoorSensor 12
#define FlameSensor 34

#define DHTTYPE DHT11

DHT dht(DHTPIN,DHTTYPE);

void setup() {
  pinMode(2,OUTPUT);
  pinMode(15,OUTPUT);
  pinMode(DoorSensor,INPUT_PULLUP);
  pinMode(FlameSensor,INPUT);
  Serial.begin(9600);
  // This delay gives the chance to wait for a Serial Monitor without blocking if none is found
  delay(1500);
  
  dht.begin();

  // Defined in thingProperties.h
  initProperties();

  // Connect to Arduino IoT Cloud
  ArduinoCloud.begin(ArduinoIoTPreferredConnection);
  
  /*
     The following function allows you to obtain more information
     related to the state of network and IoT Cloud connection and errors
     the higher number the more granular information you’ll get.
     The default is 0 (only errors).
     Maximum is 4
 */
  setDebugMessageLevel(2);
  ArduinoCloud.printDebugInfo();
}

void LED01Change()  {
  if(lED01 == HIGH){
    digitalWrite(2,HIGH);
  }
  else{
    digitalWrite(2,LOW);
  }
}

void DHT_SENSOR_READ(){
  float t = dht.readTemperature();
  temperature = t;
  float h = dht.readHumidity();
  humidity = h;
  Serial.print("Temperature: "); Serial.println(t);
  Serial.print("Humidity: "); Serial.println(h);
  delay(500);
}

void DOOR_SENSOR_READ(){
  if(digitalRead(DoorSensor)==LOW){
    door = LOW;
    Serial.println("Door Closed");
  }
  else{
    door = HIGH;
    Serial.println("Door Opened");
  }
}

void FLAME_SENSOR_READ(){
  int flame_value = analogRead(FlameSensor);
  flame_value = map(flame_value, 0, 4095, 0, 180);
  flame = flame_value;
  Serial.print("Flame : ");
  Serial.println(flame);
  delay(500);
}

void loop() {
  ArduinoCloud.update();
  // Your code here 
  DHT_SENSOR_READ();
  DOOR_SENSOR_READ();
  FLAME_SENSOR_READ();
  LED01Change();
  
  
}







/*
  Since LED01 is READ_WRITE variable, onLED01Change() is
  executed every time a new value is received from IoT Cloud.
*/
void onLED01Change()  {
  // Add your code here to act upon LED01 change
}
