// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char DEVICE_LOGIN_NAME[]  = "17718f70-ea27-42b0-95c8-1ecf75017362";

const char SSID[]               = SECRET_SSID;    // Network SSID (name)
const char PASS[]               = SECRET_OPTIONAL_PASS;    // Network password (use for WPA, or use as key for WEP)
const char DEVICE_KEY[]         = SECRET_DEVICE_KEY;    // Secret device password

void onLEDChange();

int fLAME;
bool dOOR;
bool gAS;
bool lED;
bool pIR;
CloudTemperatureSensor tEMPERATURE;
CloudRelativeHumidity hHUMIDITY;
int wATER;

void initProperties(){

  ArduinoCloud.setBoardId(DEVICE_LOGIN_NAME);
  ArduinoCloud.setSecretDeviceKey(DEVICE_KEY);
  ArduinoCloud.addProperty(fLAME, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(dOOR, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(gAS, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(lED, READWRITE, ON_CHANGE, onLEDChange);
  ArduinoCloud.addProperty(pIR, READ, ON_CHANGE, NULL);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
